export const acceptAllCookie = () => cy.get('button[id="onetrust-accept-btn-handler"]')
export const rejectAllCookie = () => cy.get('button[id="onetrust-reject-all-handler"]')
export const managePreferences = () => cy.get('button[id="onetrust-pc-btn-handler"]')
export const closeCookie = () => cy.get('button[class*="onetrus')
export const buttonLoginIn = () => cy.get('a[data-uuid*="login"]')
